service:
  name: core-service-discovery

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: source/handler.hello
    events:
      - http:
          method: get
          path: hello

  service-get:
    handler: source/catalog/service-get.main
    events:
      - http:
          method: get
          path: catalog/service
