import {
    attribute,
    autoGeneratedHashKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';
import { CreateTableOptions, GlobalSecondaryIndexOptions, PerIndexOptions } from '@aws/dynamodb-data-mapper';

@table('ServiceCatalog')
export class CatalogServiceModel {
    @autoGeneratedHashKey()
    public ServiceID: string;

    @attribute({defaultProvider: () => new Date()})
    public CreatedAt: Date;

    @attribute({
        indexKeyConfigurations: {
            ServiceNameIndex: 'HASH'
        }
    })
    public ServiceName: string;

    @attribute({
        indexKeyConfigurations: {
            ServiceNameIndex: 'RANGE'
        }
    })
    public StageName?: string;

    @attribute()
    public ServiceURL: string;

    @attribute()
    public ExternalID?: string;

    @attribute()
    public Version?: string;
}

export function TableOptions() {
    // Global secondary indexes
    const ServiceNameIndex: GlobalSecondaryIndexOptions = {
        projection: 'all',
        readCapacityUnits: 1,
        type: 'global',
        writeCapacityUnits: 1
    };

    const options: CreateTableOptions = {
        indexOptions: {
            ServiceNameIndex
        },
        readCapacityUnits: 1,
        writeCapacityUnits: 1
    };
    return options;
}
