import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';

@table('ServiceCatalog')
export default class CatalogServiceModel {
    @autoGeneratedHashKey()
    public ServiceID: string;

    @rangeKey({defaultProvider: () => new Date()})
    public CreatedAt: Date;

    @attribute()
    public ServiceName: string;

    @attribute()
    public StageName: string;

    @attribute()
    public ServiceURL: string;
}
