import {
    autoGeneratedHashKey,
    attribute,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('ServiceCatalog')
export default class CatalogServiceModel {
    @autoGeneratedHashKey()
    id: string;

    @rangeKey({defaultProvider: () => new Date()})
    createdAt: Date;

    @attribute()
    serviceName: string;

    @attribute()
    stage: string;
}
